/*Populaste Tabla Cliente*/
INSERT INTO cliente (documento, nombres, apellidos, numero_contacto, direccion, correo, codigo_postal)  VALUES(1094248825, 'Andres', 'Guzman', '3102496515', 'san pedro', 'profesor@bolsadeideas.com', '540001');
INSERT INTO cliente (documento, nombres, apellidos, numero_contacto, direccion, correo, codigo_postal)  VALUES(1094248823, 'sergio', 'bateca', '3102496515', 'san pedro', 'sergio@bolsadeideas.com', '540001');
INSERT INTO cliente (documento, nombres, apellidos, numero_contacto, direccion, correo, codigo_postal)  VALUES(1094248825, 'Andres', 'Guzman', '3102496515', 'san pedro', 'profesor@bolsadeideas.com', '540001');
INSERT INTO cliente (documento, nombres, apellidos, numero_contacto, direccion, correo, codigo_postal)  VALUES(1094248823, 'sergio', 'bateca', '3102496515', 'san pedro', 'sergio@bolsadeideas.com', '540001');
INSERT INTO departamento(nombre) VALUES('ANTIOQUIA');
INSERT INTO departamento(nombre) VALUES('ATLÁNTICO');
INSERT INTO departamento(nombre) VALUES('BOGOTÁ, D.C.');
INSERT INTO departamento(nombre) VALUES('BOLÍVAR');
INSERT INTO departamento(nombre) VALUES('BOYACÁ');
INSERT INTO departamento(nombre) VALUES('CALDAS');
INSERT INTO departamento(nombre) VALUES('CAQUETÁ');
INSERT INTO departamento(nombre) VALUES('CAUCA');
INSERT INTO departamento(nombre) VALUES('CESAR');
INSERT INTO departamento(nombre) VALUES('CÓRDOBA');
INSERT INTO departamento(nombre) VALUES('CUNDINAMARCA');
INSERT INTO departamento(nombre) VALUES('CHOCÓ');
INSERT INTO departamento(nombre) VALUES('HUILA');
INSERT INTO departamento(nombre) VALUES('LA GUAJIRA');
INSERT INTO departamento(nombre) VALUES('MAGDALENA');
INSERT INTO departamento(nombre) VALUES('META');
INSERT INTO departamento(nombre) VALUES('NARIÑO');
INSERT INTO departamento(nombre) VALUES('NORTE DE SANTANDER');
INSERT INTO departamento(nombre) VALUES('QUINDIO');
INSERT INTO departamento(nombre) VALUES('RISARALDA');
INSERT INTO departamento(nombre) VALUES('SANTANDER');
INSERT INTO departamento(nombre) VALUES('SUCRE');
INSERT INTO departamento(nombre) VALUES('TOLIMA');
INSERT INTO departamento(nombre) VALUES('VALLE DEL CAUCA');
INSERT INTO departamento(nombre) VALUES('ARAUCA');
INSERT INTO departamento(nombre) VALUES('CASANARE');
INSERT INTO departamento(nombre) VALUES('PUTUMAYO');
INSERT INTO departamento(nombre) VALUES('ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA');
INSERT INTO departamento(nombre) VALUES('AMAZONAS');
INSERT INTO departamento(nombre) VALUES('GUAINÍA');
INSERT INTO departamento(nombre) VALUES('GUAVIARE');
INSERT INTO departamento(nombre) VALUES('VAUPÉS');
INSERT INTO departamento(nombre) VALUES('VICHADA');


