

INSERT INTO departamento(id, nombre)VALUES(5,'ANTIOQUIA');
INSERT INTO departamento(id, nombre)VALUES(8,'ATLANTICO');
INSERT INTO departamento(id, nombre)VALUES(11,'BOGOTA, D.C.');
INSERT INTO departamento(id, nombre)VALUES(13,'BOLIVAR');
INSERT INTO departamento(id, nombre)VALUES(15,'BOYACA');
INSERT INTO departamento(id, nombre)VALUES(17,'CALDAS');
INSERT INTO departamento(id, nombre)VALUES(18,'CAQUETA');
INSERT INTO departamento(id, nombre)VALUES(19,'CAUCA');
INSERT INTO departamento(id, nombre)VALUES(20,'CESAR');
INSERT INTO departamento(id, nombre)VALUES(23,'CORDOBA');
INSERT INTO departamento(id, nombre)VALUES(25,'CUNDINAMARCA');
INSERT INTO departamento(id, nombre)VALUES(27,'CHOCO');
INSERT INTO departamento(id, nombre)VALUES(41,'HUILA');
INSERT INTO departamento(id, nombre)VALUES(44,'LA GUAJIRA');
INSERT INTO departamento(id, nombre)VALUES(47,'MAGDALENA');
INSERT INTO departamento(id, nombre)VALUES(50,'META');
INSERT INTO departamento(id, nombre)VALUES(52,'NARINO');
INSERT INTO departamento(id, nombre)VALUES(54,'NORTE DE SANTANDER');
INSERT INTO departamento(id, nombre)VALUES(63,'QUINDIO');
INSERT INTO departamento(id, nombre)VALUES(66,'RISARALDA');
INSERT INTO departamento(id, nombre)VALUES(68,'SANTANDER');
INSERT INTO departamento(id, nombre)VALUES(70,'SUCRE');
INSERT INTO departamento(id, nombre)VALUES(73,'TOLIMA');
INSERT INTO departamento(id, nombre)VALUES(76,'VALLE DEL CAUCA');
INSERT INTO departamento(id, nombre)VALUES(81,'ARAUCA');
INSERT INTO departamento(id, nombre)VALUES(85,'CASANARE');
INSERT INTO departamento(id, nombre)VALUES(86,'PUTUMAYO');
INSERT INTO departamento(id, nombre)VALUES(88,'ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA');
INSERT INTO departamento(id, nombre)VALUES(91,'AMAZONAS');
INSERT INTO departamento(id, nombre)VALUES(94,'GUAINIA');
INSERT INTO departamento(id, nombre)VALUES(95,'GUAVIARE');
INSERT INTO departamento(id, nombre)VALUES(97,'VAUPES');
INSERT INTO departamento(id, nombre)VALUES(99,'VICHADA');

INSERT INTO ciudad (nombre, departamento_id) VALUES ('Abriaqui', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Acacias', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Acandi', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Acevedo', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Achi', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Agrado', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Agua de Dios', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aguachica', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aguada', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aguadas', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aguazul', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Agustin Codazzi', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aipe', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Albania', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Albania', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Albania', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alban', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alban (San Jose)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alcala', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alejandria', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Algarrobo', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Algeciras', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Almaguer', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Almeida', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alpujarra', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Altamira', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alto Baudo (Pie de Pato)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Altos del Rosario', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Alvarado', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Amaga', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Amalfi', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ambalema', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anapoima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ancuya', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Andalucia', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Andes', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Angelopolis', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Angostura', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anolaima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anori', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anserma', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ansermanuevo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anzoategui', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Anza', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Apartado', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Apulo', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Apia', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aquitania', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aracataca', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aranzazu', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Aratoca', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arauca', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arauquita', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arbelaez', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arboleda (Berruecos)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arboledas', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arboletes', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arcabuco', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arenal', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Argelia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Argelia', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Argelia', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ariguani (El Dificil)', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arjona', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Armenia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Armenia', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Armero (Guayabal)', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Arroyohondo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Astrea', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ataco', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Atrato (Yuto)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ayapel', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bagado', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bahia Solano (Mutis)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bajo Baudo (Pizarro)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Balboa', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Balboa', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Baranoa', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Baraya', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barbacoas', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barbosa', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barbosa', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barichara', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barranca de Upia', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barrancabermeja', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barrancas', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barranco de Loba', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Barranquilla', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Becerril', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belalcazar', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bello', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belmira', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Beltran', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belen', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belen', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belen de Bajira', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belen de Umbria', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Belen de los Andaquies', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Berbeo', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Betania', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Beteitiva', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Betulia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Betulia', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bituima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Boavita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bochalema', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bogota D.C.', 11);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bojaca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bojaya (Bellavista)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bolivar', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bolivar', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bolivar', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bolivar', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bosconia', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Boyaca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Briceno', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Briceno', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bucaramanga', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bucarasica', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenaventura', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenavista', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenavista', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenavista', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenavista', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buenos Aires', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buesaco', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buga', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Bugalagrande', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Buritica', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Busbanza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cabrera', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cabrera', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cabuyaro', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cachipay', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caicedo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caicedonia', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caimito', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cajamarca', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cajibio', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cajica', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Calamar', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Calamar', 95);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Calarca', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caldas', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caldas', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caldono', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('California', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Calima (Darien)', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caloto', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cali', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Campamento', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Campo de la Cruz', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Campoalegre', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Campohermoso', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Canalete', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Candelaria', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Candelaria', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cantagallo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Canton de San Pablo', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caparrapi', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Capitanejo', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caracoli', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caramanta', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carcasi', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carepa', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carmen de Apicala', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carmen de Carupa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carmen de Viboral', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carmen del Darien (CURBARADO)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Carolina', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cartagena', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cartagena del Chaira', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cartago', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caruru', 97);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Casabianca', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Castilla la Nueva', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caucasia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Canasgordas', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cepita', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cerete', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cerinza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cerrito', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cerro San Antonio', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chachagui', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chaguani', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chalan', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chaparral', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Charala', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Charta', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chigorodo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chima', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chimichagua', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chima', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chinavita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chinchina', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chinacota', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chinu', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chipaque', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chipata', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chiquinquira', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chiriguana', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chiscas', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chitaga', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chitaraque', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chivata', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chivolo', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Choachi', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Choconta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chameza', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chia', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chiquiza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Chivor', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cicuco', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cimitarra', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Circasia', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cisneros', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cienaga', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cienaga', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cienaga de Oro', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Clemencia', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cocorna', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Coello', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cogua', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Colombia', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Coloso (Ricaurte)', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Colon', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Colon (Genova)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Concepcion', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Concepcion', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Concordia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Concordia', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Condoto', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Confines', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Consaca', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Contadero', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Contratacion', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Convencion', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Copacabana', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Coper', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cordoba', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Corinto', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Coromoro', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Corozal', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Corrales', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cota', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cotorra', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Covarachia', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Covenas', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Coyaima', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cravo Norte', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cuaspud (Carlosama)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cubarral', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cubara', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cucaita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cucunuba', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cucutilla', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cuitiva', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cumaral', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cumaribo', 99);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cumbal', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cumbitara', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cunday', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Curillo', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Curiti', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Curumani', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caceres', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cachira', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cacota', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Caqueza', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Certegui', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Combita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cordoba', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cordoba', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Cucuta', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Dabeiba', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Dagua', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Dibulla', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Distraccion', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Dolores', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Don Matias', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Dos Quebradas', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Duitama', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Durania', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ebejico', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Bagre', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Banco', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Cairo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Calvario', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Carmen', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Carmen', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Carmen de Atrato', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Carmen de Bolivar', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Castillo', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Cerrito', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Charco', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Cocuy', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Colegio', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Copey', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Doncello', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Dorado', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Dovio', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Espino', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Guacamayo', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Guamo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Molino', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Paso', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Paujil', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Penol', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Penon', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Penon', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Penon', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Pinon', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Playon', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Retorno', 95);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Reten', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Roble', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Rosal', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Rosario', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Tablon de Gomez', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Tambo', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Tambo', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Tarra', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Zulia', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('El Aguila', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Elias', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Encino', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Enciso', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Entrerrios', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Envigado', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Espinal', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Facatativa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Falan', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Filadelfia', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Filandia', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Firavitoba', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Flandes', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Florencia', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Florencia', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Floresta', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Florida', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Floridablanca', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Florian', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fonseca', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fortul', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fosca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Francisco Pizarro', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fredonia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fresno', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Frontino', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fuente de Oro', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fundacion', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Funes', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Funza', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fusagasuga', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fomeque', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Fuquene', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gachala', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gachancipa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gachantiva', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gacheta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Galapa', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Galeras (Nueva Granada)', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Galan', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gama', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gamarra', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Garagoa', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Garzon', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gigante', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ginebra', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Giraldo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Girardot', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Girardota', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Giron', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gonzalez', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gramalote', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Granada', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Granada', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Granada', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guaca', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guacamayas', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guacari', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guachaves', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guachene', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guacheta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guachucal', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guadalupe', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guadalupe', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guadalupe', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guaduas', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guaitarilla', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gualmatan', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guamal', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guamal', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guamo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guapota', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guapi', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guaranda', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guarne', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guasca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guatape', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guataqui', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guatavita', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guateque', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guavata', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guayabal de Siquima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guayabetal', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guayata', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guepsa', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guican', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gutierrez', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Guatica', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gambita', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gameza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Genova', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Gomez Plata', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hacari', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hatillo de Loba', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hato', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hato Corozal', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hatonuevo', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Heliconia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Herran', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Herveo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hispania', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Hobo', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Honda', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ibague', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Icononzo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Iles', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Imues', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Inza', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Inirida', 94);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ipiales', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Isnos', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Istmina', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Itagui', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ituango', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Iza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jambalo', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jamundi', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jardin', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jenesano', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jerico', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jerico', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jerusalen', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jesus Maria', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jordan', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Juan de Acosta', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Junin', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Jurado', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Apartada y La Frontera', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Argentina', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Belleza', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Calera', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Capilla', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Ceja', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Celia', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Cruz', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Cumbre', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Dorada', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Esperanza', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Estrella', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Florida', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Gloria', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Jagua de Ibirico', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Jagua del Pilar', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Llanada', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Macarena', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Merced', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Mesa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Montanita', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Palma', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Paz', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Paz (Robles)', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Pena', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Pintada', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Plata', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Playa', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Primavera', 99);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Salina', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Sierra', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Tebaida', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Tola', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Union', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Union', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Union', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Union', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Uvita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Vega', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Vega', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Victoria', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Victoria', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Victoria', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('La Virginia', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Labateca', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Labranzagrande', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Landazuri', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lebrija', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Leiva', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lejanias', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lenguazaque', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Leticia', 91);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Liborina', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Linares', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lloro', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lorica', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Los Cordobas', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Los Palmitos', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Los Patios', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Los Santos', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lourdes', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Luruaco', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lerida', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Libano', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Lopez (Micay)', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Macanal', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Macaravita', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Maceo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Macheta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Madrid', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Magangue', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Magui (Payan)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mahates', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Maicao', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Majagual', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Malambo', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mallama (Piedrancha)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manati', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manaure', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manaure Balcon del Cesar', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manizales', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Manzanares', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mani', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mapiripan', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Margarita', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Marinilla', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Maripi', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mariquita', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Marmato', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Marquetalia', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Marsella', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Marulanda', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Maria la Baja', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Matanza', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Medellin', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Medina', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Medio Atrato', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Medio Baudo', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Medio San Juan (ANDAGOYA)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Melgar', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mercaderes', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mesetas', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Milan', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Miraflores', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Miraflores', 95);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Miranda', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mistrato', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mitu',97);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mocoa', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mogotes', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Molagavita', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Momil', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mompos', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mongua', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mongui', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Moniquira', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Montebello', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Montecristo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Montelibano', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Montenegro', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Monteria', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Monterrey', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Morales', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Morales', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Morelia', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Morroa', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mosquera', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mosquera', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Motavita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Monitos', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Murillo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Murindo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mutata', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Mutiscua', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Muzo', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Malaga', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Narino', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Narino', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Narino', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Natagaima', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nechi', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Necocli', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Neira', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Neiva', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nemocon', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nilo', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nimaima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nobsa', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nocaima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Norcasia', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Norosi', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Novita', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nueva Granada', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nuevo Colon', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nunchia', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nuqui', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Nataga', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Obando', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ocamonte', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ocana', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Oiba', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Oicata', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Olaya', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Olaya Herrera', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Onzaga', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Oporapa', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Orito', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Orocue', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ortega', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ospina', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Otanche', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ovejas', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pachavita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pacho', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Padilla', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paicol', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pailitas', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paime', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paipa', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pajarito', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palermo', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palestina', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palestina', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palmar', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palmar de Varela', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palmas del Socorro', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palmira', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palmito', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Palocabildo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pamplona', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pamplonita', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pandi', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Panqueba', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paratebueno', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pasca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Patia (El Bordo)', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pauna', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paya', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paz de Ariporo', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paz de Rio', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pedraza', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pelaya', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pensilvania', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Peque', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pereira', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pesca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Penol', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Piamonte', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pie de Cuesta', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Piedras', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Piendamo', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pijao', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pijino', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pinchote', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pinillos', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Piojo', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pisva', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pital', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pitalito', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pivijay', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Planadas', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Planeta Rica', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Plato', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Policarpa', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Polonuevo', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ponedera', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Popayan', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pore', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Potosi', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pradera', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Prado', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Providencia', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Providencia', 88);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pueblo Bello', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pueblo Nuevo', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pueblo Rico', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pueblorrico', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puebloviejo', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puente Nacional', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerres', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Asis', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Berrio', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Boyaca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Caicedo', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Carreno', 99);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Colombia', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Concordia', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Escondido', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Gaitan', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Guzman', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Leguizamo', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Libertador', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Lleras', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Lopez', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Nare', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Narino', 91);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Parra', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Rico', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Rico', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Rondon', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Salgar', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Santander', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Tejada', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Triunfo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puerto Wilches', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Puli', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pupiales', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Purace (Coconuco)', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Purificacion', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Purisima', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Pacora', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paez', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paez (Belalcazar)', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Paramo', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quebradanegra', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quetame', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quibdo', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quimbaya', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quinchia', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quipama', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Quipile', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ragonvalia', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ramiriqui', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Recetor', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Regidor', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Remedios', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Remolino', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Repelon', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Restrepo', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Restrepo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Retiro', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ricaurte', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ricaurte', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio Negro', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rioblanco', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Riofrio', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Riohacha', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Risaralda', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rivera', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Roberto Payan (San Jose)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Roldanillo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Roncesvalles', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rondon', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rosas', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rovira', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Raquira', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio Iro', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio Quito', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio Sucio', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio Viejo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rio de oro', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Rionegro', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Riosucio', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabana de Torres', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabanagrande', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabanalarga', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabanalarga', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabanalarga', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabanas de San Angel (SAN ANGEL)', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sabaneta', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Saboya', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sahagun', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Saladoblanco', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Salamina', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Salamina', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Salazar', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Saldana', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Salento', 63);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Salgar', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Samaca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Samaniego', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Samana', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sampues', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Agustin', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Alberto', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Andres', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Andres Sotavento', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Andres de Cuerquia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Antero', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Antonio', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Antonio de Tequendama', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Benito', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Benito Abad', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Bernardo', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Bernardo', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Bernardo del Viento', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Calixto', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Carlos', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Carlos', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Carlos de Guaroa', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Cayetano', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Cayetano', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Cristobal', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Diego', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Eduardo', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Estanislao', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Fernando', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Francisco', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Francisco', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Francisco', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Gil', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jacinto', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jacinto del Cauca', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jeronimo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Joaquin', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose de Miranda', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose de Montana', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose de Pare', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose de Ure', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose del Fragua', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose del Guaviare', 95);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Jose del Palmar', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Arama', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Betulia', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Nepomuceno', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Pasto', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Rio Seco', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan de Uraba', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juan del Cesar', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Juanito', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Lorenzo', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Luis', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Luis', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Luis de Gaceno', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Luis de Palenque', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Marcos', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Martin', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Martin', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Martin de Loba', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Mateo', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Miguel', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Miguel', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Miguel de Sema', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Onofre', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pablo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pablo', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pablo de Borbur', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pedro', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pedro', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pedro', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pedro de Cartago', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pedro de Uraba', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Pelayo', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Rafael', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Roque', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Sebastian', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Sebastian de Buenavista', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Vicente', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Vicente del Caguan', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Vicente del Chucuri', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('San Zenon', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sandona', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Ana', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Barbara', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Barbara', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Barbara (Iscuande)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Barbara de Pinto', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Catalina', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Fe de Antioquia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Genoveva de Docorodo', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Helena del Opon', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Isabel', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Lucia', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Marta', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Maria', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Maria', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa de Cabal', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa de Osos', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa de Viterbo', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosa del Sur', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Rosalia', 99);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santa Sofia', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santana', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santander de Quilichao', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santiago', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santiago', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santo Domingo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santo Tomas', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santuario', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Santuario', 66);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sapuyes', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Saravena', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sardinata', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sasaima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sativanorte', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sativasur', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Segovia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sesquile', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sevilla', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Siachoque', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sibate', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sibundoy', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Silos', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Silvania', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Silvia', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Simacota', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Simijaca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Simiti', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sincelejo', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Since', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sipi', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sitionuevo', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Soacha', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Soata', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Socha', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Socorro', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Socota', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sogamaoso', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Solano', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Soledad', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Solita', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Somondoco', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sonson', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sopetran', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Soplaviento', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sopo', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sora', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Soraca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sotaquira', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sotara (Paispamba)', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sotomayor (Los Andes)', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suaita', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suan', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suaza', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Subachoque', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sucre', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sucre', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sucre', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suesca', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Supata', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Supia', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Surata', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Susa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Susacon', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sutamarchan', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sutatausa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sutatenza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suarez', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Suarez', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sacama', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Sachica', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tabio', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tado', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Talaigua Nuevo', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tamalameque', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tame', 81);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Taminango', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tangua', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Taraira', 97);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Taraza', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tarqui', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tarso', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tasco', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tauramena', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tausa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tello', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tena', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tenerife', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tenjo', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tenza', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Teorama', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Teruel', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tesalia', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tibacuy', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tibana', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tibasosa', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tibirita', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tibu', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tierralta', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Timana', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Timbiqui', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Timbio', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tinjaca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tipacoque', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tiquisio (Puerto Rico)', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Titiribi', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Toca', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tocaima', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tocancipa', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Togui', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Toledo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Toledo', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tolu', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tolu Viejo', 70);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tona', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Topaga', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Topaipi', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Toribio', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Toro', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tota', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Totoro', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Trinidad', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Trujillo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tubara', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tuchin', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tulua', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tumaco', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tunja', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tunungua', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Turbaco', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Turbana', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Turbo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Turmeque', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tuta', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tutasa', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tamara', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tmesis', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Tuquerres', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ubala', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ubaque', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ubate', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ulloa', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Une', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Unguia', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Union Panamericana (ANIMAS)', 27);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Uramita', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Uribe', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Uribia', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Urrao', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Urumita', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Usiacuri', 8);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valdivia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valencia', 23);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valle de San Jose', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valle de San Juan', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valle del Guamuez', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valledupar', 20);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valparaiso', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Valparaiso', 18);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vegachi', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Venadillo', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Venecia', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Venecia (Ospina Perez)', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Ventaquemada', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vergara', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Versalles', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vetas', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Viani', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vigia del Fuerte', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vijes', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villa Caro', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villa Rica', 19);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villa de Leiva', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villa del Rosario', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villagarzon', 86);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villagomez', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villahermosa', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villamaria', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villanueva', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villanueva', 44);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villanueva', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villanueva', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villapinzon', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villarrica', 73);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villavicencio', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villavieja', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Villeta', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Viota', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Viracacha' , 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Vista Hermosa', 50);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Viterbo', 17);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Velez', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yacopi', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yacuanquer', 52);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yaguara', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yali', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yarumal', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yolombo', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yondo (Casabe)', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yopal', 85);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yotoco', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Yumbo', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zambrano', 13);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zapatoca', 68);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zapayan (PUNTA DE PIEDRAS)', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zaragoza', 5);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zarzal', 76);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zetaquira', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zipacon', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zipaquira', 25);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Zona Bananera (PRADO - SEVILLA)', 47);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Abrego', 54);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Iquira', 41);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Umbita', 15);
INSERT INTO ciudad (nombre, departamento_id) VALUES ('Utica', 25);

/*Populaste Tabla Cliente*/

INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Ramón','Valencia',21345,60300300,301456721,'ramon@proveedor.com','calle 25 No. 25-25');
INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Julio','Ortiz',232324,1094246587,310123456,'julio@proveedor.com','calle 25 No. 25-25');
INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Andrea','Benanidez',13354678,6030300,315458712,'andrea@proveedor.com','calle 25 No. 25-25');
INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Julio','Pérez',1255489,1234657,311245369,'juliop@proveedor.com','calle 25 No. 25-25');
INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Carlos','Barriga',24855,12346789,312456789,'calos@proveedor.com','calle 25 No. 25-25');
INSERT INTO proveedores (nombres, apellidos, nit, documento, numero_contacto, correo_electronico, direccion_residencia) VALUES ('Smith','Jhonson',254152,1234857885,300124596,'smith@proveedor.com','calle 25 No. 25-25');


/*inserts tabla tallas*/
INSERT INTO tallas(talla,descripcion) VALUES (35,'Talla 35 americana');
INSERT INTO tallas(talla,descripcion) VALUES (36,'Talla 36 americana');
INSERT INTO tallas(talla,descripcion) VALUES (37,'Talla 37 americana');
INSERT INTO tallas(talla,descripcion) VALUES (38,'Talla 38 americana');
INSERT INTO tallas(talla,descripcion) VALUES (39,'Talla 39 americana');
